platform :ios, '11.0'
use_frameworks!

def common_pods
    pod 'SwiftyBeaver'
end

target 'NewsReader' do
    common_pods
    pod 'Kingfisher'
end

target 'NewsReaderTests' do
    common_pods
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
end
